version: '2'
services:
  proxy:
    image: nginx
    ports:
        - "80"
    links:
        - apollo
        - galaxy
    volumes:
        - "./nginx/conf:/etc/nginx/conf.d"
  galaxy:
    image: quay.io/erasche/docker-galaxy-annotation
    environment:
        NONUSE: nodejs,proftp,reports
        GALAXY_LOGGING: full
        GALAXY_WEBAPOLLO_URL: "http://apollo:8080/apollo"
        GALAXY_WEBAPOLLO_EXT_URL: "/apollo"
        GALAXY_WEBAPOLLO_PASSWORD: "password"
        GALAXY_WEBAPOLLO_USER: admin@local.host
        GALAXY_SHARED_DIR: /apollo-data
  apollo:
    image: quay.io/erasche/apollo:master
    links:
      - "apollo_db:db"
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
    volumes_from:
        - "galaxy:rw"
    command: "chmod 777 /apollo-data"
  apollo_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
